CREATE TABLE `personnel` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(255) NOT NULL,
  `middle_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) NOT NULL,
  `name_suffix` varchar(255) DEFAULT NULL,
  `address1` varchar(255) DEFAULT NULL,
  `address2` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `postal_code` varchar(255) DEFAULT NULL,
  `zip_code` varchar(255) DEFAULT NULL,
  `phone_num_primary` varchar(255) DEFAULT NULL,
  `phone_num_alt` varchar(255) DEFAULT NULL,
  `email_address` varchar(255) DEFAULT NULL,
  `position_descr` varchar(255) NOT NULL,
  `reports_to_id` int(11) DEFAULT NULL,
  `remarks` text,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `reports_to_id` (`reports_to_id`),
  CONSTRAINT `personnel_ibfk_1` FOREIGN KEY (`reports_to_id`) REFERENCES `personnel` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1